environment:
  DYNAMODB_TABLE_GENE_UTTERANCES: quiz-gene-utterances-${self:provider.stage}
  DYNAMODB_TABLE_CANCER_UTTERANCES: quiz-cancer-utterances-${self:provider.stage}
  DYNAMODB_TABLE_EXPERT_UTTERANCES: quiz-expert-utterances-${self:provider.stage}
  DYNAMODB_TABLE_TEST_UTTERANCES: quiz-test-utterances-${self:provider.stage}
  S3_BUCKET_EXPERT_AUDIO: ${self:service}-expert-audio-${self:provider.stage}
  MELVIN_REST_API_ENDPOINT: "https://api.dev.melvin.pittlabgenomics.com/v0.1"

alexa:
  appId: amzn1.ask.skill.c2b58adb-5811-4416-9b5d-22df8a87de7d