environment:
  DYNAMODB_TABLE_GENE_UTTERANCES: quiz-gene-utterances-${self:provider.stage}
  DYNAMODB_TABLE_CANCER_UTTERANCES: quiz-cancer-utterances-${self:provider.stage}
  DYNAMODB_TABLE_CATEGORY_UTTERANCES: quiz-category-utterances-${self:provider.stage}
  DYNAMODB_TABLE_EXPERT_UTTERANCES: quiz-expert-utterances-${self:provider.stage}
  DYNAMODB_TABLE_TEST_UTTERANCES: quiz-test-utterances-${self:provider.stage}
  S3_BUCKET_EXPERT_AUDIO: ${self:service}-expert-audio-${self:provider.stage}
  MELVIN_REST_API_ENDPOINT: "https://api.uat.melvin.pittlabgenomics.com/v0.1"
  OOV_MAPPER_ENDPOINT: "https://api.uat.oovm-fg.pittlabgenomics.com/v0.0.1/"

alexa:
  appId: amzn1.ask.skill.d3ba13c7-1d2a-4d76-8b6a-1c2ed64e9866